platform :ios, "7.0"


targetsArray = ['LYSCalendar']

targetsArray.each do |t|
    target t do
        
        pod 'Masonry', '~> 1.0.1'
        
        pod 'pop', '~> 1.0.9'
        
        
        pod 'PLeakSniffer', :git => 'https://github.com/music4kid/PLeakSniffer.git', :tag => '0.1.0'
        
        
    end
end



